name: Python Check

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

jobs:
  check-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Check Python Syntax
      run: |
        python -m compileall .